// Code generated by ent, DO NOT EDIT.

package group

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the group type in the database.
	Label = "group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeLineusers holds the string denoting the lineusers edge name in mutations.
	EdgeLineusers = "lineusers"
	// Table holds the table name of the group in the database.
	Table = "groups"
	// LineusersTable is the table that holds the lineusers relation/edge. The primary key declared below.
	LineusersTable = "group_lineusers"
	// LineusersInverseTable is the table name for the LineUser entity.
	// It exists in this package in order to avoid circular dependency with the "lineuser" package.
	LineusersInverseTable = "line_users"
)

// Columns holds all SQL columns for group fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// LineusersPrimaryKey and LineusersColumn2 are the table columns denoting the
	// primary key for the lineusers relation (M2M).
	LineusersPrimaryKey = []string{"group_id", "line_user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Group queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLineusersCount orders the results by lineusers count.
func ByLineusersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLineusersStep(), opts...)
	}
}

// ByLineusers orders the results by lineusers terms.
func ByLineusers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLineusersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLineusersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LineusersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, LineusersTable, LineusersPrimaryKey...),
	)
}
