// Code generated by ent, DO NOT EDIT.

package creditlater

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the creditlater type in the database.
	Label = "credit_later"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTransactionRef holds the string denoting the transaction_ref field in the database.
	FieldTransactionRef = "transaction_ref"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldBranch holds the string denoting the branch field in the database.
	FieldBranch = "branch"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldInstallment holds the string denoting the installment field in the database.
	FieldInstallment = "installment"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the creditlater in the database.
	Table = "credit_laters"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "credit_laters"
	// OwnerInverseTable is the table name for the LineUser entity.
	// It exists in this package in order to avoid circular dependency with the "lineuser" package.
	OwnerInverseTable = "line_users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "line_user_creditlaters"
)

// Columns holds all SQL columns for creditlater fields.
var Columns = []string{
	FieldID,
	FieldTransactionRef,
	FieldDate,
	FieldBranch,
	FieldAmount,
	FieldInstallment,
	FieldDetail,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "credit_laters"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"line_user_creditlaters",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TransactionRefValidator is a validator for the "transaction_ref" field. It is called by the builders before save.
	TransactionRefValidator func(string) error
	// DefaultDate holds the default value on creation for the "date" field.
	DefaultDate string
	// DefaultBranch holds the default value on creation for the "branch" field.
	DefaultBranch string
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount int
	// DefaultInstallment holds the default value on creation for the "installment" field.
	DefaultInstallment int
	// DefaultDetail holds the default value on creation for the "detail" field.
	DefaultDetail string
)

// OrderOption defines the ordering options for the CreditLater queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTransactionRef orders the results by the transaction_ref field.
func ByTransactionRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionRef, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByBranch orders the results by the branch field.
func ByBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBranch, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByInstallment orders the results by the installment field.
func ByInstallment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallment, opts...).ToFunc()
}

// ByDetail orders the results by the detail field.
func ByDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetail, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
	)
}
