// Code generated by ent, DO NOT EDIT.

package creditlater

import (
	"entdemo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLTE(FieldID, id))
}

// TransactionRef applies equality check predicate on the "transaction_ref" field. It's identical to TransactionRefEQ.
func TransactionRef(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldTransactionRef, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldDate, v))
}

// Branch applies equality check predicate on the "branch" field. It's identical to BranchEQ.
func Branch(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldBranch, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldAmount, v))
}

// Installment applies equality check predicate on the "installment" field. It's identical to InstallmentEQ.
func Installment(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldInstallment, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldDetail, v))
}

// TransactionRefEQ applies the EQ predicate on the "transaction_ref" field.
func TransactionRefEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldTransactionRef, v))
}

// TransactionRefNEQ applies the NEQ predicate on the "transaction_ref" field.
func TransactionRefNEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNEQ(FieldTransactionRef, v))
}

// TransactionRefIn applies the In predicate on the "transaction_ref" field.
func TransactionRefIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldIn(FieldTransactionRef, vs...))
}

// TransactionRefNotIn applies the NotIn predicate on the "transaction_ref" field.
func TransactionRefNotIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNotIn(FieldTransactionRef, vs...))
}

// TransactionRefGT applies the GT predicate on the "transaction_ref" field.
func TransactionRefGT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGT(FieldTransactionRef, v))
}

// TransactionRefGTE applies the GTE predicate on the "transaction_ref" field.
func TransactionRefGTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGTE(FieldTransactionRef, v))
}

// TransactionRefLT applies the LT predicate on the "transaction_ref" field.
func TransactionRefLT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLT(FieldTransactionRef, v))
}

// TransactionRefLTE applies the LTE predicate on the "transaction_ref" field.
func TransactionRefLTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLTE(FieldTransactionRef, v))
}

// TransactionRefContains applies the Contains predicate on the "transaction_ref" field.
func TransactionRefContains(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContains(FieldTransactionRef, v))
}

// TransactionRefHasPrefix applies the HasPrefix predicate on the "transaction_ref" field.
func TransactionRefHasPrefix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasPrefix(FieldTransactionRef, v))
}

// TransactionRefHasSuffix applies the HasSuffix predicate on the "transaction_ref" field.
func TransactionRefHasSuffix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasSuffix(FieldTransactionRef, v))
}

// TransactionRefEqualFold applies the EqualFold predicate on the "transaction_ref" field.
func TransactionRefEqualFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEqualFold(FieldTransactionRef, v))
}

// TransactionRefContainsFold applies the ContainsFold predicate on the "transaction_ref" field.
func TransactionRefContainsFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContainsFold(FieldTransactionRef, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLTE(FieldDate, v))
}

// DateContains applies the Contains predicate on the "date" field.
func DateContains(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContains(FieldDate, v))
}

// DateHasPrefix applies the HasPrefix predicate on the "date" field.
func DateHasPrefix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasPrefix(FieldDate, v))
}

// DateHasSuffix applies the HasSuffix predicate on the "date" field.
func DateHasSuffix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasSuffix(FieldDate, v))
}

// DateEqualFold applies the EqualFold predicate on the "date" field.
func DateEqualFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEqualFold(FieldDate, v))
}

// DateContainsFold applies the ContainsFold predicate on the "date" field.
func DateContainsFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContainsFold(FieldDate, v))
}

// BranchEQ applies the EQ predicate on the "branch" field.
func BranchEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldBranch, v))
}

// BranchNEQ applies the NEQ predicate on the "branch" field.
func BranchNEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNEQ(FieldBranch, v))
}

// BranchIn applies the In predicate on the "branch" field.
func BranchIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldIn(FieldBranch, vs...))
}

// BranchNotIn applies the NotIn predicate on the "branch" field.
func BranchNotIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNotIn(FieldBranch, vs...))
}

// BranchGT applies the GT predicate on the "branch" field.
func BranchGT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGT(FieldBranch, v))
}

// BranchGTE applies the GTE predicate on the "branch" field.
func BranchGTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGTE(FieldBranch, v))
}

// BranchLT applies the LT predicate on the "branch" field.
func BranchLT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLT(FieldBranch, v))
}

// BranchLTE applies the LTE predicate on the "branch" field.
func BranchLTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLTE(FieldBranch, v))
}

// BranchContains applies the Contains predicate on the "branch" field.
func BranchContains(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContains(FieldBranch, v))
}

// BranchHasPrefix applies the HasPrefix predicate on the "branch" field.
func BranchHasPrefix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasPrefix(FieldBranch, v))
}

// BranchHasSuffix applies the HasSuffix predicate on the "branch" field.
func BranchHasSuffix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasSuffix(FieldBranch, v))
}

// BranchEqualFold applies the EqualFold predicate on the "branch" field.
func BranchEqualFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEqualFold(FieldBranch, v))
}

// BranchContainsFold applies the ContainsFold predicate on the "branch" field.
func BranchContainsFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContainsFold(FieldBranch, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLTE(FieldAmount, v))
}

// InstallmentEQ applies the EQ predicate on the "installment" field.
func InstallmentEQ(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldInstallment, v))
}

// InstallmentNEQ applies the NEQ predicate on the "installment" field.
func InstallmentNEQ(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNEQ(FieldInstallment, v))
}

// InstallmentIn applies the In predicate on the "installment" field.
func InstallmentIn(vs ...int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldIn(FieldInstallment, vs...))
}

// InstallmentNotIn applies the NotIn predicate on the "installment" field.
func InstallmentNotIn(vs ...int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNotIn(FieldInstallment, vs...))
}

// InstallmentGT applies the GT predicate on the "installment" field.
func InstallmentGT(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGT(FieldInstallment, v))
}

// InstallmentGTE applies the GTE predicate on the "installment" field.
func InstallmentGTE(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGTE(FieldInstallment, v))
}

// InstallmentLT applies the LT predicate on the "installment" field.
func InstallmentLT(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLT(FieldInstallment, v))
}

// InstallmentLTE applies the LTE predicate on the "installment" field.
func InstallmentLTE(v int) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLTE(FieldInstallment, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.CreditLater {
	return predicate.CreditLater(sql.FieldContainsFold(FieldDetail, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.CreditLater {
	return predicate.CreditLater(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.LineUser) predicate.CreditLater {
	return predicate.CreditLater(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreditLater) predicate.CreditLater {
	return predicate.CreditLater(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreditLater) predicate.CreditLater {
	return predicate.CreditLater(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreditLater) predicate.CreditLater {
	return predicate.CreditLater(func(s *sql.Selector) {
		p(s.Not())
	})
}
