// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/creditlater"
	"entdemo/ent/lineuser"
	"entdemo/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CreditLaterUpdate is the builder for updating CreditLater entities.
type CreditLaterUpdate struct {
	config
	hooks    []Hook
	mutation *CreditLaterMutation
}

// Where appends a list predicates to the CreditLaterUpdate builder.
func (clu *CreditLaterUpdate) Where(ps ...predicate.CreditLater) *CreditLaterUpdate {
	clu.mutation.Where(ps...)
	return clu
}

// SetTransactionRef sets the "transaction_ref" field.
func (clu *CreditLaterUpdate) SetTransactionRef(s string) *CreditLaterUpdate {
	clu.mutation.SetTransactionRef(s)
	return clu
}

// SetDate sets the "date" field.
func (clu *CreditLaterUpdate) SetDate(s string) *CreditLaterUpdate {
	clu.mutation.SetDate(s)
	return clu
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (clu *CreditLaterUpdate) SetNillableDate(s *string) *CreditLaterUpdate {
	if s != nil {
		clu.SetDate(*s)
	}
	return clu
}

// SetBranch sets the "branch" field.
func (clu *CreditLaterUpdate) SetBranch(s string) *CreditLaterUpdate {
	clu.mutation.SetBranch(s)
	return clu
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (clu *CreditLaterUpdate) SetNillableBranch(s *string) *CreditLaterUpdate {
	if s != nil {
		clu.SetBranch(*s)
	}
	return clu
}

// SetAmount sets the "amount" field.
func (clu *CreditLaterUpdate) SetAmount(i int) *CreditLaterUpdate {
	clu.mutation.ResetAmount()
	clu.mutation.SetAmount(i)
	return clu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (clu *CreditLaterUpdate) SetNillableAmount(i *int) *CreditLaterUpdate {
	if i != nil {
		clu.SetAmount(*i)
	}
	return clu
}

// AddAmount adds i to the "amount" field.
func (clu *CreditLaterUpdate) AddAmount(i int) *CreditLaterUpdate {
	clu.mutation.AddAmount(i)
	return clu
}

// SetInstallment sets the "installment" field.
func (clu *CreditLaterUpdate) SetInstallment(i int) *CreditLaterUpdate {
	clu.mutation.ResetInstallment()
	clu.mutation.SetInstallment(i)
	return clu
}

// SetNillableInstallment sets the "installment" field if the given value is not nil.
func (clu *CreditLaterUpdate) SetNillableInstallment(i *int) *CreditLaterUpdate {
	if i != nil {
		clu.SetInstallment(*i)
	}
	return clu
}

// AddInstallment adds i to the "installment" field.
func (clu *CreditLaterUpdate) AddInstallment(i int) *CreditLaterUpdate {
	clu.mutation.AddInstallment(i)
	return clu
}

// SetDetail sets the "detail" field.
func (clu *CreditLaterUpdate) SetDetail(s string) *CreditLaterUpdate {
	clu.mutation.SetDetail(s)
	return clu
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (clu *CreditLaterUpdate) SetNillableDetail(s *string) *CreditLaterUpdate {
	if s != nil {
		clu.SetDetail(*s)
	}
	return clu
}

// SetOwnerID sets the "owner" edge to the LineUser entity by ID.
func (clu *CreditLaterUpdate) SetOwnerID(id int) *CreditLaterUpdate {
	clu.mutation.SetOwnerID(id)
	return clu
}

// SetNillableOwnerID sets the "owner" edge to the LineUser entity by ID if the given value is not nil.
func (clu *CreditLaterUpdate) SetNillableOwnerID(id *int) *CreditLaterUpdate {
	if id != nil {
		clu = clu.SetOwnerID(*id)
	}
	return clu
}

// SetOwner sets the "owner" edge to the LineUser entity.
func (clu *CreditLaterUpdate) SetOwner(l *LineUser) *CreditLaterUpdate {
	return clu.SetOwnerID(l.ID)
}

// Mutation returns the CreditLaterMutation object of the builder.
func (clu *CreditLaterUpdate) Mutation() *CreditLaterMutation {
	return clu.mutation
}

// ClearOwner clears the "owner" edge to the LineUser entity.
func (clu *CreditLaterUpdate) ClearOwner() *CreditLaterUpdate {
	clu.mutation.ClearOwner()
	return clu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (clu *CreditLaterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, clu.sqlSave, clu.mutation, clu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (clu *CreditLaterUpdate) SaveX(ctx context.Context) int {
	affected, err := clu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (clu *CreditLaterUpdate) Exec(ctx context.Context) error {
	_, err := clu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clu *CreditLaterUpdate) ExecX(ctx context.Context) {
	if err := clu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (clu *CreditLaterUpdate) check() error {
	if v, ok := clu.mutation.TransactionRef(); ok {
		if err := creditlater.TransactionRefValidator(v); err != nil {
			return &ValidationError{Name: "transaction_ref", err: fmt.Errorf(`ent: validator failed for field "CreditLater.transaction_ref": %w`, err)}
		}
	}
	return nil
}

func (clu *CreditLaterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := clu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(creditlater.Table, creditlater.Columns, sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt))
	if ps := clu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := clu.mutation.TransactionRef(); ok {
		_spec.SetField(creditlater.FieldTransactionRef, field.TypeString, value)
	}
	if value, ok := clu.mutation.Date(); ok {
		_spec.SetField(creditlater.FieldDate, field.TypeString, value)
	}
	if value, ok := clu.mutation.Branch(); ok {
		_spec.SetField(creditlater.FieldBranch, field.TypeString, value)
	}
	if value, ok := clu.mutation.Amount(); ok {
		_spec.SetField(creditlater.FieldAmount, field.TypeInt, value)
	}
	if value, ok := clu.mutation.AddedAmount(); ok {
		_spec.AddField(creditlater.FieldAmount, field.TypeInt, value)
	}
	if value, ok := clu.mutation.Installment(); ok {
		_spec.SetField(creditlater.FieldInstallment, field.TypeInt, value)
	}
	if value, ok := clu.mutation.AddedInstallment(); ok {
		_spec.AddField(creditlater.FieldInstallment, field.TypeInt, value)
	}
	if value, ok := clu.mutation.Detail(); ok {
		_spec.SetField(creditlater.FieldDetail, field.TypeString, value)
	}
	if clu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   creditlater.OwnerTable,
			Columns: []string{creditlater.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := clu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   creditlater.OwnerTable,
			Columns: []string{creditlater.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, clu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creditlater.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	clu.mutation.done = true
	return n, nil
}

// CreditLaterUpdateOne is the builder for updating a single CreditLater entity.
type CreditLaterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreditLaterMutation
}

// SetTransactionRef sets the "transaction_ref" field.
func (cluo *CreditLaterUpdateOne) SetTransactionRef(s string) *CreditLaterUpdateOne {
	cluo.mutation.SetTransactionRef(s)
	return cluo
}

// SetDate sets the "date" field.
func (cluo *CreditLaterUpdateOne) SetDate(s string) *CreditLaterUpdateOne {
	cluo.mutation.SetDate(s)
	return cluo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (cluo *CreditLaterUpdateOne) SetNillableDate(s *string) *CreditLaterUpdateOne {
	if s != nil {
		cluo.SetDate(*s)
	}
	return cluo
}

// SetBranch sets the "branch" field.
func (cluo *CreditLaterUpdateOne) SetBranch(s string) *CreditLaterUpdateOne {
	cluo.mutation.SetBranch(s)
	return cluo
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (cluo *CreditLaterUpdateOne) SetNillableBranch(s *string) *CreditLaterUpdateOne {
	if s != nil {
		cluo.SetBranch(*s)
	}
	return cluo
}

// SetAmount sets the "amount" field.
func (cluo *CreditLaterUpdateOne) SetAmount(i int) *CreditLaterUpdateOne {
	cluo.mutation.ResetAmount()
	cluo.mutation.SetAmount(i)
	return cluo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (cluo *CreditLaterUpdateOne) SetNillableAmount(i *int) *CreditLaterUpdateOne {
	if i != nil {
		cluo.SetAmount(*i)
	}
	return cluo
}

// AddAmount adds i to the "amount" field.
func (cluo *CreditLaterUpdateOne) AddAmount(i int) *CreditLaterUpdateOne {
	cluo.mutation.AddAmount(i)
	return cluo
}

// SetInstallment sets the "installment" field.
func (cluo *CreditLaterUpdateOne) SetInstallment(i int) *CreditLaterUpdateOne {
	cluo.mutation.ResetInstallment()
	cluo.mutation.SetInstallment(i)
	return cluo
}

// SetNillableInstallment sets the "installment" field if the given value is not nil.
func (cluo *CreditLaterUpdateOne) SetNillableInstallment(i *int) *CreditLaterUpdateOne {
	if i != nil {
		cluo.SetInstallment(*i)
	}
	return cluo
}

// AddInstallment adds i to the "installment" field.
func (cluo *CreditLaterUpdateOne) AddInstallment(i int) *CreditLaterUpdateOne {
	cluo.mutation.AddInstallment(i)
	return cluo
}

// SetDetail sets the "detail" field.
func (cluo *CreditLaterUpdateOne) SetDetail(s string) *CreditLaterUpdateOne {
	cluo.mutation.SetDetail(s)
	return cluo
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (cluo *CreditLaterUpdateOne) SetNillableDetail(s *string) *CreditLaterUpdateOne {
	if s != nil {
		cluo.SetDetail(*s)
	}
	return cluo
}

// SetOwnerID sets the "owner" edge to the LineUser entity by ID.
func (cluo *CreditLaterUpdateOne) SetOwnerID(id int) *CreditLaterUpdateOne {
	cluo.mutation.SetOwnerID(id)
	return cluo
}

// SetNillableOwnerID sets the "owner" edge to the LineUser entity by ID if the given value is not nil.
func (cluo *CreditLaterUpdateOne) SetNillableOwnerID(id *int) *CreditLaterUpdateOne {
	if id != nil {
		cluo = cluo.SetOwnerID(*id)
	}
	return cluo
}

// SetOwner sets the "owner" edge to the LineUser entity.
func (cluo *CreditLaterUpdateOne) SetOwner(l *LineUser) *CreditLaterUpdateOne {
	return cluo.SetOwnerID(l.ID)
}

// Mutation returns the CreditLaterMutation object of the builder.
func (cluo *CreditLaterUpdateOne) Mutation() *CreditLaterMutation {
	return cluo.mutation
}

// ClearOwner clears the "owner" edge to the LineUser entity.
func (cluo *CreditLaterUpdateOne) ClearOwner() *CreditLaterUpdateOne {
	cluo.mutation.ClearOwner()
	return cluo
}

// Where appends a list predicates to the CreditLaterUpdate builder.
func (cluo *CreditLaterUpdateOne) Where(ps ...predicate.CreditLater) *CreditLaterUpdateOne {
	cluo.mutation.Where(ps...)
	return cluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cluo *CreditLaterUpdateOne) Select(field string, fields ...string) *CreditLaterUpdateOne {
	cluo.fields = append([]string{field}, fields...)
	return cluo
}

// Save executes the query and returns the updated CreditLater entity.
func (cluo *CreditLaterUpdateOne) Save(ctx context.Context) (*CreditLater, error) {
	return withHooks(ctx, cluo.sqlSave, cluo.mutation, cluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cluo *CreditLaterUpdateOne) SaveX(ctx context.Context) *CreditLater {
	node, err := cluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cluo *CreditLaterUpdateOne) Exec(ctx context.Context) error {
	_, err := cluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cluo *CreditLaterUpdateOne) ExecX(ctx context.Context) {
	if err := cluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cluo *CreditLaterUpdateOne) check() error {
	if v, ok := cluo.mutation.TransactionRef(); ok {
		if err := creditlater.TransactionRefValidator(v); err != nil {
			return &ValidationError{Name: "transaction_ref", err: fmt.Errorf(`ent: validator failed for field "CreditLater.transaction_ref": %w`, err)}
		}
	}
	return nil
}

func (cluo *CreditLaterUpdateOne) sqlSave(ctx context.Context) (_node *CreditLater, err error) {
	if err := cluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creditlater.Table, creditlater.Columns, sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt))
	id, ok := cluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreditLater.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creditlater.FieldID)
		for _, f := range fields {
			if !creditlater.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creditlater.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cluo.mutation.TransactionRef(); ok {
		_spec.SetField(creditlater.FieldTransactionRef, field.TypeString, value)
	}
	if value, ok := cluo.mutation.Date(); ok {
		_spec.SetField(creditlater.FieldDate, field.TypeString, value)
	}
	if value, ok := cluo.mutation.Branch(); ok {
		_spec.SetField(creditlater.FieldBranch, field.TypeString, value)
	}
	if value, ok := cluo.mutation.Amount(); ok {
		_spec.SetField(creditlater.FieldAmount, field.TypeInt, value)
	}
	if value, ok := cluo.mutation.AddedAmount(); ok {
		_spec.AddField(creditlater.FieldAmount, field.TypeInt, value)
	}
	if value, ok := cluo.mutation.Installment(); ok {
		_spec.SetField(creditlater.FieldInstallment, field.TypeInt, value)
	}
	if value, ok := cluo.mutation.AddedInstallment(); ok {
		_spec.AddField(creditlater.FieldInstallment, field.TypeInt, value)
	}
	if value, ok := cluo.mutation.Detail(); ok {
		_spec.SetField(creditlater.FieldDetail, field.TypeString, value)
	}
	if cluo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   creditlater.OwnerTable,
			Columns: []string{creditlater.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cluo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   creditlater.OwnerTable,
			Columns: []string{creditlater.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CreditLater{config: cluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creditlater.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cluo.mutation.done = true
	return _node, nil
}
