// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entdemo/ent/creditlater"
	"entdemo/ent/lineuser"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CreditLater is the model entity for the CreditLater schema.
type CreditLater struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TransactionRef holds the value of the "transaction_ref" field.
	TransactionRef string `json:"transaction_ref,omitempty"`
	// Date holds the value of the "date" field.
	Date string `json:"date,omitempty"`
	// Branch holds the value of the "branch" field.
	Branch string `json:"branch,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int `json:"amount,omitempty"`
	// Installment holds the value of the "installment" field.
	Installment int `json:"installment,omitempty"`
	// Detail holds the value of the "detail" field.
	Detail string `json:"detail,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CreditLaterQuery when eager-loading is set.
	Edges                  CreditLaterEdges `json:"edges"`
	line_user_creditlaters *int
	selectValues           sql.SelectValues
}

// CreditLaterEdges holds the relations/edges for other nodes in the graph.
type CreditLaterEdges struct {
	// Owner holds the value of the owner edge.
	Owner *LineUser `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CreditLaterEdges) OwnerOrErr() (*LineUser, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: lineuser.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreditLater) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creditlater.FieldID, creditlater.FieldAmount, creditlater.FieldInstallment:
			values[i] = new(sql.NullInt64)
		case creditlater.FieldTransactionRef, creditlater.FieldDate, creditlater.FieldBranch, creditlater.FieldDetail:
			values[i] = new(sql.NullString)
		case creditlater.ForeignKeys[0]: // line_user_creditlaters
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreditLater fields.
func (cl *CreditLater) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creditlater.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cl.ID = int(value.Int64)
		case creditlater.FieldTransactionRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_ref", values[i])
			} else if value.Valid {
				cl.TransactionRef = value.String
			}
		case creditlater.FieldDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				cl.Date = value.String
			}
		case creditlater.FieldBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch", values[i])
			} else if value.Valid {
				cl.Branch = value.String
			}
		case creditlater.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				cl.Amount = int(value.Int64)
			}
		case creditlater.FieldInstallment:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field installment", values[i])
			} else if value.Valid {
				cl.Installment = int(value.Int64)
			}
		case creditlater.FieldDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detail", values[i])
			} else if value.Valid {
				cl.Detail = value.String
			}
		case creditlater.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field line_user_creditlaters", value)
			} else if value.Valid {
				cl.line_user_creditlaters = new(int)
				*cl.line_user_creditlaters = int(value.Int64)
			}
		default:
			cl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreditLater.
// This includes values selected through modifiers, order, etc.
func (cl *CreditLater) Value(name string) (ent.Value, error) {
	return cl.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the CreditLater entity.
func (cl *CreditLater) QueryOwner() *LineUserQuery {
	return NewCreditLaterClient(cl.config).QueryOwner(cl)
}

// Update returns a builder for updating this CreditLater.
// Note that you need to call CreditLater.Unwrap() before calling this method if this CreditLater
// was returned from a transaction, and the transaction was committed or rolled back.
func (cl *CreditLater) Update() *CreditLaterUpdateOne {
	return NewCreditLaterClient(cl.config).UpdateOne(cl)
}

// Unwrap unwraps the CreditLater entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cl *CreditLater) Unwrap() *CreditLater {
	_tx, ok := cl.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreditLater is not a transactional entity")
	}
	cl.config.driver = _tx.drv
	return cl
}

// String implements the fmt.Stringer.
func (cl *CreditLater) String() string {
	var builder strings.Builder
	builder.WriteString("CreditLater(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cl.ID))
	builder.WriteString("transaction_ref=")
	builder.WriteString(cl.TransactionRef)
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(cl.Date)
	builder.WriteString(", ")
	builder.WriteString("branch=")
	builder.WriteString(cl.Branch)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", cl.Amount))
	builder.WriteString(", ")
	builder.WriteString("installment=")
	builder.WriteString(fmt.Sprintf("%v", cl.Installment))
	builder.WriteString(", ")
	builder.WriteString("detail=")
	builder.WriteString(cl.Detail)
	builder.WriteByte(')')
	return builder.String()
}

// CreditLaters is a parsable slice of CreditLater.
type CreditLaters []*CreditLater
