// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/creditlater"
	"entdemo/ent/lineuser"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CreditLaterCreate is the builder for creating a CreditLater entity.
type CreditLaterCreate struct {
	config
	mutation *CreditLaterMutation
	hooks    []Hook
}

// SetTransactionRef sets the "transaction_ref" field.
func (clc *CreditLaterCreate) SetTransactionRef(s string) *CreditLaterCreate {
	clc.mutation.SetTransactionRef(s)
	return clc
}

// SetDate sets the "date" field.
func (clc *CreditLaterCreate) SetDate(s string) *CreditLaterCreate {
	clc.mutation.SetDate(s)
	return clc
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (clc *CreditLaterCreate) SetNillableDate(s *string) *CreditLaterCreate {
	if s != nil {
		clc.SetDate(*s)
	}
	return clc
}

// SetBranch sets the "branch" field.
func (clc *CreditLaterCreate) SetBranch(s string) *CreditLaterCreate {
	clc.mutation.SetBranch(s)
	return clc
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (clc *CreditLaterCreate) SetNillableBranch(s *string) *CreditLaterCreate {
	if s != nil {
		clc.SetBranch(*s)
	}
	return clc
}

// SetAmount sets the "amount" field.
func (clc *CreditLaterCreate) SetAmount(i int) *CreditLaterCreate {
	clc.mutation.SetAmount(i)
	return clc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (clc *CreditLaterCreate) SetNillableAmount(i *int) *CreditLaterCreate {
	if i != nil {
		clc.SetAmount(*i)
	}
	return clc
}

// SetInstallment sets the "installment" field.
func (clc *CreditLaterCreate) SetInstallment(i int) *CreditLaterCreate {
	clc.mutation.SetInstallment(i)
	return clc
}

// SetNillableInstallment sets the "installment" field if the given value is not nil.
func (clc *CreditLaterCreate) SetNillableInstallment(i *int) *CreditLaterCreate {
	if i != nil {
		clc.SetInstallment(*i)
	}
	return clc
}

// SetDetail sets the "detail" field.
func (clc *CreditLaterCreate) SetDetail(s string) *CreditLaterCreate {
	clc.mutation.SetDetail(s)
	return clc
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (clc *CreditLaterCreate) SetNillableDetail(s *string) *CreditLaterCreate {
	if s != nil {
		clc.SetDetail(*s)
	}
	return clc
}

// SetOwnerID sets the "owner" edge to the LineUser entity by ID.
func (clc *CreditLaterCreate) SetOwnerID(id int) *CreditLaterCreate {
	clc.mutation.SetOwnerID(id)
	return clc
}

// SetNillableOwnerID sets the "owner" edge to the LineUser entity by ID if the given value is not nil.
func (clc *CreditLaterCreate) SetNillableOwnerID(id *int) *CreditLaterCreate {
	if id != nil {
		clc = clc.SetOwnerID(*id)
	}
	return clc
}

// SetOwner sets the "owner" edge to the LineUser entity.
func (clc *CreditLaterCreate) SetOwner(l *LineUser) *CreditLaterCreate {
	return clc.SetOwnerID(l.ID)
}

// Mutation returns the CreditLaterMutation object of the builder.
func (clc *CreditLaterCreate) Mutation() *CreditLaterMutation {
	return clc.mutation
}

// Save creates the CreditLater in the database.
func (clc *CreditLaterCreate) Save(ctx context.Context) (*CreditLater, error) {
	clc.defaults()
	return withHooks(ctx, clc.sqlSave, clc.mutation, clc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (clc *CreditLaterCreate) SaveX(ctx context.Context) *CreditLater {
	v, err := clc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (clc *CreditLaterCreate) Exec(ctx context.Context) error {
	_, err := clc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clc *CreditLaterCreate) ExecX(ctx context.Context) {
	if err := clc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (clc *CreditLaterCreate) defaults() {
	if _, ok := clc.mutation.Date(); !ok {
		v := creditlater.DefaultDate
		clc.mutation.SetDate(v)
	}
	if _, ok := clc.mutation.Branch(); !ok {
		v := creditlater.DefaultBranch
		clc.mutation.SetBranch(v)
	}
	if _, ok := clc.mutation.Amount(); !ok {
		v := creditlater.DefaultAmount
		clc.mutation.SetAmount(v)
	}
	if _, ok := clc.mutation.Installment(); !ok {
		v := creditlater.DefaultInstallment
		clc.mutation.SetInstallment(v)
	}
	if _, ok := clc.mutation.Detail(); !ok {
		v := creditlater.DefaultDetail
		clc.mutation.SetDetail(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (clc *CreditLaterCreate) check() error {
	if _, ok := clc.mutation.TransactionRef(); !ok {
		return &ValidationError{Name: "transaction_ref", err: errors.New(`ent: missing required field "CreditLater.transaction_ref"`)}
	}
	if v, ok := clc.mutation.TransactionRef(); ok {
		if err := creditlater.TransactionRefValidator(v); err != nil {
			return &ValidationError{Name: "transaction_ref", err: fmt.Errorf(`ent: validator failed for field "CreditLater.transaction_ref": %w`, err)}
		}
	}
	if _, ok := clc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "CreditLater.date"`)}
	}
	if _, ok := clc.mutation.Branch(); !ok {
		return &ValidationError{Name: "branch", err: errors.New(`ent: missing required field "CreditLater.branch"`)}
	}
	if _, ok := clc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CreditLater.amount"`)}
	}
	if _, ok := clc.mutation.Installment(); !ok {
		return &ValidationError{Name: "installment", err: errors.New(`ent: missing required field "CreditLater.installment"`)}
	}
	if _, ok := clc.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "CreditLater.detail"`)}
	}
	return nil
}

func (clc *CreditLaterCreate) sqlSave(ctx context.Context) (*CreditLater, error) {
	if err := clc.check(); err != nil {
		return nil, err
	}
	_node, _spec := clc.createSpec()
	if err := sqlgraph.CreateNode(ctx, clc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	clc.mutation.id = &_node.ID
	clc.mutation.done = true
	return _node, nil
}

func (clc *CreditLaterCreate) createSpec() (*CreditLater, *sqlgraph.CreateSpec) {
	var (
		_node = &CreditLater{config: clc.config}
		_spec = sqlgraph.NewCreateSpec(creditlater.Table, sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt))
	)
	if value, ok := clc.mutation.TransactionRef(); ok {
		_spec.SetField(creditlater.FieldTransactionRef, field.TypeString, value)
		_node.TransactionRef = value
	}
	if value, ok := clc.mutation.Date(); ok {
		_spec.SetField(creditlater.FieldDate, field.TypeString, value)
		_node.Date = value
	}
	if value, ok := clc.mutation.Branch(); ok {
		_spec.SetField(creditlater.FieldBranch, field.TypeString, value)
		_node.Branch = value
	}
	if value, ok := clc.mutation.Amount(); ok {
		_spec.SetField(creditlater.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := clc.mutation.Installment(); ok {
		_spec.SetField(creditlater.FieldInstallment, field.TypeInt, value)
		_node.Installment = value
	}
	if value, ok := clc.mutation.Detail(); ok {
		_spec.SetField(creditlater.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if nodes := clc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   creditlater.OwnerTable,
			Columns: []string{creditlater.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.line_user_creditlaters = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CreditLaterCreateBulk is the builder for creating many CreditLater entities in bulk.
type CreditLaterCreateBulk struct {
	config
	builders []*CreditLaterCreate
}

// Save creates the CreditLater entities in the database.
func (clcb *CreditLaterCreateBulk) Save(ctx context.Context) ([]*CreditLater, error) {
	specs := make([]*sqlgraph.CreateSpec, len(clcb.builders))
	nodes := make([]*CreditLater, len(clcb.builders))
	mutators := make([]Mutator, len(clcb.builders))
	for i := range clcb.builders {
		func(i int, root context.Context) {
			builder := clcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditLaterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, clcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, clcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, clcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (clcb *CreditLaterCreateBulk) SaveX(ctx context.Context) []*CreditLater {
	v, err := clcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (clcb *CreditLaterCreateBulk) Exec(ctx context.Context) error {
	_, err := clcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clcb *CreditLaterCreateBulk) ExecX(ctx context.Context) {
	if err := clcb.Exec(ctx); err != nil {
		panic(err)
	}
}
