// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/linelog"
	"entdemo/ent/lineuser"
	"entdemo/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineLogUpdate is the builder for updating LineLog entities.
type LineLogUpdate struct {
	config
	hooks    []Hook
	mutation *LineLogMutation
}

// Where appends a list predicates to the LineLogUpdate builder.
func (llu *LineLogUpdate) Where(ps ...predicate.LineLog) *LineLogUpdate {
	llu.mutation.Where(ps...)
	return llu
}

// SetAction sets the "action" field.
func (llu *LineLogUpdate) SetAction(s string) *LineLogUpdate {
	llu.mutation.SetAction(s)
	return llu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (llu *LineLogUpdate) SetNillableAction(s *string) *LineLogUpdate {
	if s != nil {
		llu.SetAction(*s)
	}
	return llu
}

// SetMessage sets the "message" field.
func (llu *LineLogUpdate) SetMessage(s string) *LineLogUpdate {
	llu.mutation.SetMessage(s)
	return llu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (llu *LineLogUpdate) SetNillableMessage(s *string) *LineLogUpdate {
	if s != nil {
		llu.SetMessage(*s)
	}
	return llu
}

// SetCreatedAt sets the "created_at" field.
func (llu *LineLogUpdate) SetCreatedAt(t time.Time) *LineLogUpdate {
	llu.mutation.SetCreatedAt(t)
	return llu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (llu *LineLogUpdate) SetNillableCreatedAt(t *time.Time) *LineLogUpdate {
	if t != nil {
		llu.SetCreatedAt(*t)
	}
	return llu
}

// SetOwnerID sets the "owner" edge to the LineUser entity by ID.
func (llu *LineLogUpdate) SetOwnerID(id int) *LineLogUpdate {
	llu.mutation.SetOwnerID(id)
	return llu
}

// SetNillableOwnerID sets the "owner" edge to the LineUser entity by ID if the given value is not nil.
func (llu *LineLogUpdate) SetNillableOwnerID(id *int) *LineLogUpdate {
	if id != nil {
		llu = llu.SetOwnerID(*id)
	}
	return llu
}

// SetOwner sets the "owner" edge to the LineUser entity.
func (llu *LineLogUpdate) SetOwner(l *LineUser) *LineLogUpdate {
	return llu.SetOwnerID(l.ID)
}

// Mutation returns the LineLogMutation object of the builder.
func (llu *LineLogUpdate) Mutation() *LineLogMutation {
	return llu.mutation
}

// ClearOwner clears the "owner" edge to the LineUser entity.
func (llu *LineLogUpdate) ClearOwner() *LineLogUpdate {
	llu.mutation.ClearOwner()
	return llu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (llu *LineLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, llu.sqlSave, llu.mutation, llu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (llu *LineLogUpdate) SaveX(ctx context.Context) int {
	affected, err := llu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (llu *LineLogUpdate) Exec(ctx context.Context) error {
	_, err := llu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (llu *LineLogUpdate) ExecX(ctx context.Context) {
	if err := llu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (llu *LineLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(linelog.Table, linelog.Columns, sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt))
	if ps := llu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := llu.mutation.Action(); ok {
		_spec.SetField(linelog.FieldAction, field.TypeString, value)
	}
	if value, ok := llu.mutation.Message(); ok {
		_spec.SetField(linelog.FieldMessage, field.TypeString, value)
	}
	if value, ok := llu.mutation.CreatedAt(); ok {
		_spec.SetField(linelog.FieldCreatedAt, field.TypeTime, value)
	}
	if llu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linelog.OwnerTable,
			Columns: []string{linelog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := llu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linelog.OwnerTable,
			Columns: []string{linelog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, llu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	llu.mutation.done = true
	return n, nil
}

// LineLogUpdateOne is the builder for updating a single LineLog entity.
type LineLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LineLogMutation
}

// SetAction sets the "action" field.
func (lluo *LineLogUpdateOne) SetAction(s string) *LineLogUpdateOne {
	lluo.mutation.SetAction(s)
	return lluo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (lluo *LineLogUpdateOne) SetNillableAction(s *string) *LineLogUpdateOne {
	if s != nil {
		lluo.SetAction(*s)
	}
	return lluo
}

// SetMessage sets the "message" field.
func (lluo *LineLogUpdateOne) SetMessage(s string) *LineLogUpdateOne {
	lluo.mutation.SetMessage(s)
	return lluo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (lluo *LineLogUpdateOne) SetNillableMessage(s *string) *LineLogUpdateOne {
	if s != nil {
		lluo.SetMessage(*s)
	}
	return lluo
}

// SetCreatedAt sets the "created_at" field.
func (lluo *LineLogUpdateOne) SetCreatedAt(t time.Time) *LineLogUpdateOne {
	lluo.mutation.SetCreatedAt(t)
	return lluo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lluo *LineLogUpdateOne) SetNillableCreatedAt(t *time.Time) *LineLogUpdateOne {
	if t != nil {
		lluo.SetCreatedAt(*t)
	}
	return lluo
}

// SetOwnerID sets the "owner" edge to the LineUser entity by ID.
func (lluo *LineLogUpdateOne) SetOwnerID(id int) *LineLogUpdateOne {
	lluo.mutation.SetOwnerID(id)
	return lluo
}

// SetNillableOwnerID sets the "owner" edge to the LineUser entity by ID if the given value is not nil.
func (lluo *LineLogUpdateOne) SetNillableOwnerID(id *int) *LineLogUpdateOne {
	if id != nil {
		lluo = lluo.SetOwnerID(*id)
	}
	return lluo
}

// SetOwner sets the "owner" edge to the LineUser entity.
func (lluo *LineLogUpdateOne) SetOwner(l *LineUser) *LineLogUpdateOne {
	return lluo.SetOwnerID(l.ID)
}

// Mutation returns the LineLogMutation object of the builder.
func (lluo *LineLogUpdateOne) Mutation() *LineLogMutation {
	return lluo.mutation
}

// ClearOwner clears the "owner" edge to the LineUser entity.
func (lluo *LineLogUpdateOne) ClearOwner() *LineLogUpdateOne {
	lluo.mutation.ClearOwner()
	return lluo
}

// Where appends a list predicates to the LineLogUpdate builder.
func (lluo *LineLogUpdateOne) Where(ps ...predicate.LineLog) *LineLogUpdateOne {
	lluo.mutation.Where(ps...)
	return lluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lluo *LineLogUpdateOne) Select(field string, fields ...string) *LineLogUpdateOne {
	lluo.fields = append([]string{field}, fields...)
	return lluo
}

// Save executes the query and returns the updated LineLog entity.
func (lluo *LineLogUpdateOne) Save(ctx context.Context) (*LineLog, error) {
	return withHooks(ctx, lluo.sqlSave, lluo.mutation, lluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lluo *LineLogUpdateOne) SaveX(ctx context.Context) *LineLog {
	node, err := lluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lluo *LineLogUpdateOne) Exec(ctx context.Context) error {
	_, err := lluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lluo *LineLogUpdateOne) ExecX(ctx context.Context) {
	if err := lluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lluo *LineLogUpdateOne) sqlSave(ctx context.Context) (_node *LineLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(linelog.Table, linelog.Columns, sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt))
	id, ok := lluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LineLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linelog.FieldID)
		for _, f := range fields {
			if !linelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != linelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lluo.mutation.Action(); ok {
		_spec.SetField(linelog.FieldAction, field.TypeString, value)
	}
	if value, ok := lluo.mutation.Message(); ok {
		_spec.SetField(linelog.FieldMessage, field.TypeString, value)
	}
	if value, ok := lluo.mutation.CreatedAt(); ok {
		_spec.SetField(linelog.FieldCreatedAt, field.TypeTime, value)
	}
	if lluo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linelog.OwnerTable,
			Columns: []string{linelog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lluo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linelog.OwnerTable,
			Columns: []string{linelog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LineLog{config: lluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lluo.mutation.done = true
	return _node, nil
}
