// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/creditlater"
	"entdemo/ent/linelog"
	"entdemo/ent/lineuser"
	"entdemo/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineUserUpdate is the builder for updating LineUser entities.
type LineUserUpdate struct {
	config
	hooks    []Hook
	mutation *LineUserMutation
}

// Where appends a list predicates to the LineUserUpdate builder.
func (luu *LineUserUpdate) Where(ps ...predicate.LineUser) *LineUserUpdate {
	luu.mutation.Where(ps...)
	return luu
}

// SetUserId sets the "userId" field.
func (luu *LineUserUpdate) SetUserId(s string) *LineUserUpdate {
	luu.mutation.SetUserId(s)
	return luu
}

// SetDisplyaName sets the "displyaName" field.
func (luu *LineUserUpdate) SetDisplyaName(s string) *LineUserUpdate {
	luu.mutation.SetDisplyaName(s)
	return luu
}

// SetRegisteredAt sets the "registered_at" field.
func (luu *LineUserUpdate) SetRegisteredAt(t time.Time) *LineUserUpdate {
	luu.mutation.SetRegisteredAt(t)
	return luu
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (luu *LineUserUpdate) SetNillableRegisteredAt(t *time.Time) *LineUserUpdate {
	if t != nil {
		luu.SetRegisteredAt(*t)
	}
	return luu
}

// SetActive sets the "active" field.
func (luu *LineUserUpdate) SetActive(b bool) *LineUserUpdate {
	luu.mutation.SetActive(b)
	return luu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (luu *LineUserUpdate) SetNillableActive(b *bool) *LineUserUpdate {
	if b != nil {
		luu.SetActive(*b)
	}
	return luu
}

// AddLinelogIDs adds the "linelogs" edge to the LineLog entity by IDs.
func (luu *LineUserUpdate) AddLinelogIDs(ids ...int) *LineUserUpdate {
	luu.mutation.AddLinelogIDs(ids...)
	return luu
}

// AddLinelogs adds the "linelogs" edges to the LineLog entity.
func (luu *LineUserUpdate) AddLinelogs(l ...*LineLog) *LineUserUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luu.AddLinelogIDs(ids...)
}

// SetCreditlatersID sets the "creditlaters" edge to the CreditLater entity by ID.
func (luu *LineUserUpdate) SetCreditlatersID(id int) *LineUserUpdate {
	luu.mutation.SetCreditlatersID(id)
	return luu
}

// SetNillableCreditlatersID sets the "creditlaters" edge to the CreditLater entity by ID if the given value is not nil.
func (luu *LineUserUpdate) SetNillableCreditlatersID(id *int) *LineUserUpdate {
	if id != nil {
		luu = luu.SetCreditlatersID(*id)
	}
	return luu
}

// SetCreditlaters sets the "creditlaters" edge to the CreditLater entity.
func (luu *LineUserUpdate) SetCreditlaters(c *CreditLater) *LineUserUpdate {
	return luu.SetCreditlatersID(c.ID)
}

// Mutation returns the LineUserMutation object of the builder.
func (luu *LineUserUpdate) Mutation() *LineUserMutation {
	return luu.mutation
}

// ClearLinelogs clears all "linelogs" edges to the LineLog entity.
func (luu *LineUserUpdate) ClearLinelogs() *LineUserUpdate {
	luu.mutation.ClearLinelogs()
	return luu
}

// RemoveLinelogIDs removes the "linelogs" edge to LineLog entities by IDs.
func (luu *LineUserUpdate) RemoveLinelogIDs(ids ...int) *LineUserUpdate {
	luu.mutation.RemoveLinelogIDs(ids...)
	return luu
}

// RemoveLinelogs removes "linelogs" edges to LineLog entities.
func (luu *LineUserUpdate) RemoveLinelogs(l ...*LineLog) *LineUserUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luu.RemoveLinelogIDs(ids...)
}

// ClearCreditlaters clears the "creditlaters" edge to the CreditLater entity.
func (luu *LineUserUpdate) ClearCreditlaters() *LineUserUpdate {
	luu.mutation.ClearCreditlaters()
	return luu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (luu *LineUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, luu.sqlSave, luu.mutation, luu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luu *LineUserUpdate) SaveX(ctx context.Context) int {
	affected, err := luu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (luu *LineUserUpdate) Exec(ctx context.Context) error {
	_, err := luu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luu *LineUserUpdate) ExecX(ctx context.Context) {
	if err := luu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luu *LineUserUpdate) check() error {
	if v, ok := luu.mutation.UserId(); ok {
		if err := lineuser.UserIdValidator(v); err != nil {
			return &ValidationError{Name: "userId", err: fmt.Errorf(`ent: validator failed for field "LineUser.userId": %w`, err)}
		}
	}
	return nil
}

func (luu *LineUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := luu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(lineuser.Table, lineuser.Columns, sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt))
	if ps := luu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luu.mutation.UserId(); ok {
		_spec.SetField(lineuser.FieldUserId, field.TypeString, value)
	}
	if value, ok := luu.mutation.DisplyaName(); ok {
		_spec.SetField(lineuser.FieldDisplyaName, field.TypeString, value)
	}
	if value, ok := luu.mutation.RegisteredAt(); ok {
		_spec.SetField(lineuser.FieldRegisteredAt, field.TypeTime, value)
	}
	if value, ok := luu.mutation.Active(); ok {
		_spec.SetField(lineuser.FieldActive, field.TypeBool, value)
	}
	if luu.mutation.LinelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.LinelogsTable,
			Columns: []string{lineuser.LinelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luu.mutation.RemovedLinelogsIDs(); len(nodes) > 0 && !luu.mutation.LinelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.LinelogsTable,
			Columns: []string{lineuser.LinelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luu.mutation.LinelogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.LinelogsTable,
			Columns: []string{lineuser.LinelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luu.mutation.CreditlatersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lineuser.CreditlatersTable,
			Columns: []string{lineuser.CreditlatersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luu.mutation.CreditlatersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lineuser.CreditlatersTable,
			Columns: []string{lineuser.CreditlatersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, luu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lineuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	luu.mutation.done = true
	return n, nil
}

// LineUserUpdateOne is the builder for updating a single LineUser entity.
type LineUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LineUserMutation
}

// SetUserId sets the "userId" field.
func (luuo *LineUserUpdateOne) SetUserId(s string) *LineUserUpdateOne {
	luuo.mutation.SetUserId(s)
	return luuo
}

// SetDisplyaName sets the "displyaName" field.
func (luuo *LineUserUpdateOne) SetDisplyaName(s string) *LineUserUpdateOne {
	luuo.mutation.SetDisplyaName(s)
	return luuo
}

// SetRegisteredAt sets the "registered_at" field.
func (luuo *LineUserUpdateOne) SetRegisteredAt(t time.Time) *LineUserUpdateOne {
	luuo.mutation.SetRegisteredAt(t)
	return luuo
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (luuo *LineUserUpdateOne) SetNillableRegisteredAt(t *time.Time) *LineUserUpdateOne {
	if t != nil {
		luuo.SetRegisteredAt(*t)
	}
	return luuo
}

// SetActive sets the "active" field.
func (luuo *LineUserUpdateOne) SetActive(b bool) *LineUserUpdateOne {
	luuo.mutation.SetActive(b)
	return luuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (luuo *LineUserUpdateOne) SetNillableActive(b *bool) *LineUserUpdateOne {
	if b != nil {
		luuo.SetActive(*b)
	}
	return luuo
}

// AddLinelogIDs adds the "linelogs" edge to the LineLog entity by IDs.
func (luuo *LineUserUpdateOne) AddLinelogIDs(ids ...int) *LineUserUpdateOne {
	luuo.mutation.AddLinelogIDs(ids...)
	return luuo
}

// AddLinelogs adds the "linelogs" edges to the LineLog entity.
func (luuo *LineUserUpdateOne) AddLinelogs(l ...*LineLog) *LineUserUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luuo.AddLinelogIDs(ids...)
}

// SetCreditlatersID sets the "creditlaters" edge to the CreditLater entity by ID.
func (luuo *LineUserUpdateOne) SetCreditlatersID(id int) *LineUserUpdateOne {
	luuo.mutation.SetCreditlatersID(id)
	return luuo
}

// SetNillableCreditlatersID sets the "creditlaters" edge to the CreditLater entity by ID if the given value is not nil.
func (luuo *LineUserUpdateOne) SetNillableCreditlatersID(id *int) *LineUserUpdateOne {
	if id != nil {
		luuo = luuo.SetCreditlatersID(*id)
	}
	return luuo
}

// SetCreditlaters sets the "creditlaters" edge to the CreditLater entity.
func (luuo *LineUserUpdateOne) SetCreditlaters(c *CreditLater) *LineUserUpdateOne {
	return luuo.SetCreditlatersID(c.ID)
}

// Mutation returns the LineUserMutation object of the builder.
func (luuo *LineUserUpdateOne) Mutation() *LineUserMutation {
	return luuo.mutation
}

// ClearLinelogs clears all "linelogs" edges to the LineLog entity.
func (luuo *LineUserUpdateOne) ClearLinelogs() *LineUserUpdateOne {
	luuo.mutation.ClearLinelogs()
	return luuo
}

// RemoveLinelogIDs removes the "linelogs" edge to LineLog entities by IDs.
func (luuo *LineUserUpdateOne) RemoveLinelogIDs(ids ...int) *LineUserUpdateOne {
	luuo.mutation.RemoveLinelogIDs(ids...)
	return luuo
}

// RemoveLinelogs removes "linelogs" edges to LineLog entities.
func (luuo *LineUserUpdateOne) RemoveLinelogs(l ...*LineLog) *LineUserUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luuo.RemoveLinelogIDs(ids...)
}

// ClearCreditlaters clears the "creditlaters" edge to the CreditLater entity.
func (luuo *LineUserUpdateOne) ClearCreditlaters() *LineUserUpdateOne {
	luuo.mutation.ClearCreditlaters()
	return luuo
}

// Where appends a list predicates to the LineUserUpdate builder.
func (luuo *LineUserUpdateOne) Where(ps ...predicate.LineUser) *LineUserUpdateOne {
	luuo.mutation.Where(ps...)
	return luuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luuo *LineUserUpdateOne) Select(field string, fields ...string) *LineUserUpdateOne {
	luuo.fields = append([]string{field}, fields...)
	return luuo
}

// Save executes the query and returns the updated LineUser entity.
func (luuo *LineUserUpdateOne) Save(ctx context.Context) (*LineUser, error) {
	return withHooks(ctx, luuo.sqlSave, luuo.mutation, luuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luuo *LineUserUpdateOne) SaveX(ctx context.Context) *LineUser {
	node, err := luuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luuo *LineUserUpdateOne) Exec(ctx context.Context) error {
	_, err := luuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luuo *LineUserUpdateOne) ExecX(ctx context.Context) {
	if err := luuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luuo *LineUserUpdateOne) check() error {
	if v, ok := luuo.mutation.UserId(); ok {
		if err := lineuser.UserIdValidator(v); err != nil {
			return &ValidationError{Name: "userId", err: fmt.Errorf(`ent: validator failed for field "LineUser.userId": %w`, err)}
		}
	}
	return nil
}

func (luuo *LineUserUpdateOne) sqlSave(ctx context.Context) (_node *LineUser, err error) {
	if err := luuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lineuser.Table, lineuser.Columns, sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt))
	id, ok := luuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LineUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lineuser.FieldID)
		for _, f := range fields {
			if !lineuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lineuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luuo.mutation.UserId(); ok {
		_spec.SetField(lineuser.FieldUserId, field.TypeString, value)
	}
	if value, ok := luuo.mutation.DisplyaName(); ok {
		_spec.SetField(lineuser.FieldDisplyaName, field.TypeString, value)
	}
	if value, ok := luuo.mutation.RegisteredAt(); ok {
		_spec.SetField(lineuser.FieldRegisteredAt, field.TypeTime, value)
	}
	if value, ok := luuo.mutation.Active(); ok {
		_spec.SetField(lineuser.FieldActive, field.TypeBool, value)
	}
	if luuo.mutation.LinelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.LinelogsTable,
			Columns: []string{lineuser.LinelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luuo.mutation.RemovedLinelogsIDs(); len(nodes) > 0 && !luuo.mutation.LinelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.LinelogsTable,
			Columns: []string{lineuser.LinelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luuo.mutation.LinelogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.LinelogsTable,
			Columns: []string{lineuser.LinelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luuo.mutation.CreditlatersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lineuser.CreditlatersTable,
			Columns: []string{lineuser.CreditlatersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luuo.mutation.CreditlatersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lineuser.CreditlatersTable,
			Columns: []string{lineuser.CreditlatersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LineUser{config: luuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lineuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luuo.mutation.done = true
	return _node, nil
}
