// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/lineuser"
	"entdemo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineUserDelete is the builder for deleting a LineUser entity.
type LineUserDelete struct {
	config
	hooks    []Hook
	mutation *LineUserMutation
}

// Where appends a list predicates to the LineUserDelete builder.
func (lud *LineUserDelete) Where(ps ...predicate.LineUser) *LineUserDelete {
	lud.mutation.Where(ps...)
	return lud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lud *LineUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lud.sqlExec, lud.mutation, lud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lud *LineUserDelete) ExecX(ctx context.Context) int {
	n, err := lud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lud *LineUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(lineuser.Table, sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt))
	if ps := lud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lud.mutation.done = true
	return affected, err
}

// LineUserDeleteOne is the builder for deleting a single LineUser entity.
type LineUserDeleteOne struct {
	lud *LineUserDelete
}

// Where appends a list predicates to the LineUserDelete builder.
func (ludo *LineUserDeleteOne) Where(ps ...predicate.LineUser) *LineUserDeleteOne {
	ludo.lud.mutation.Where(ps...)
	return ludo
}

// Exec executes the deletion query.
func (ludo *LineUserDeleteOne) Exec(ctx context.Context) error {
	n, err := ludo.lud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lineuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ludo *LineUserDeleteOne) ExecX(ctx context.Context) {
	if err := ludo.Exec(ctx); err != nil {
		panic(err)
	}
}
