// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/linelog"
	"entdemo/ent/lineuser"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineLogCreate is the builder for creating a LineLog entity.
type LineLogCreate struct {
	config
	mutation *LineLogMutation
	hooks    []Hook
}

// SetAction sets the "action" field.
func (llc *LineLogCreate) SetAction(s string) *LineLogCreate {
	llc.mutation.SetAction(s)
	return llc
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (llc *LineLogCreate) SetNillableAction(s *string) *LineLogCreate {
	if s != nil {
		llc.SetAction(*s)
	}
	return llc
}

// SetMessage sets the "message" field.
func (llc *LineLogCreate) SetMessage(s string) *LineLogCreate {
	llc.mutation.SetMessage(s)
	return llc
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (llc *LineLogCreate) SetNillableMessage(s *string) *LineLogCreate {
	if s != nil {
		llc.SetMessage(*s)
	}
	return llc
}

// SetCreatedAt sets the "created_at" field.
func (llc *LineLogCreate) SetCreatedAt(t time.Time) *LineLogCreate {
	llc.mutation.SetCreatedAt(t)
	return llc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (llc *LineLogCreate) SetNillableCreatedAt(t *time.Time) *LineLogCreate {
	if t != nil {
		llc.SetCreatedAt(*t)
	}
	return llc
}

// SetOwnerID sets the "owner" edge to the LineUser entity by ID.
func (llc *LineLogCreate) SetOwnerID(id int) *LineLogCreate {
	llc.mutation.SetOwnerID(id)
	return llc
}

// SetNillableOwnerID sets the "owner" edge to the LineUser entity by ID if the given value is not nil.
func (llc *LineLogCreate) SetNillableOwnerID(id *int) *LineLogCreate {
	if id != nil {
		llc = llc.SetOwnerID(*id)
	}
	return llc
}

// SetOwner sets the "owner" edge to the LineUser entity.
func (llc *LineLogCreate) SetOwner(l *LineUser) *LineLogCreate {
	return llc.SetOwnerID(l.ID)
}

// Mutation returns the LineLogMutation object of the builder.
func (llc *LineLogCreate) Mutation() *LineLogMutation {
	return llc.mutation
}

// Save creates the LineLog in the database.
func (llc *LineLogCreate) Save(ctx context.Context) (*LineLog, error) {
	llc.defaults()
	return withHooks(ctx, llc.sqlSave, llc.mutation, llc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (llc *LineLogCreate) SaveX(ctx context.Context) *LineLog {
	v, err := llc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (llc *LineLogCreate) Exec(ctx context.Context) error {
	_, err := llc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (llc *LineLogCreate) ExecX(ctx context.Context) {
	if err := llc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (llc *LineLogCreate) defaults() {
	if _, ok := llc.mutation.Action(); !ok {
		v := linelog.DefaultAction
		llc.mutation.SetAction(v)
	}
	if _, ok := llc.mutation.Message(); !ok {
		v := linelog.DefaultMessage
		llc.mutation.SetMessage(v)
	}
	if _, ok := llc.mutation.CreatedAt(); !ok {
		v := linelog.DefaultCreatedAt
		llc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (llc *LineLogCreate) check() error {
	if _, ok := llc.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "LineLog.action"`)}
	}
	if _, ok := llc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "LineLog.message"`)}
	}
	if _, ok := llc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LineLog.created_at"`)}
	}
	return nil
}

func (llc *LineLogCreate) sqlSave(ctx context.Context) (*LineLog, error) {
	if err := llc.check(); err != nil {
		return nil, err
	}
	_node, _spec := llc.createSpec()
	if err := sqlgraph.CreateNode(ctx, llc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	llc.mutation.id = &_node.ID
	llc.mutation.done = true
	return _node, nil
}

func (llc *LineLogCreate) createSpec() (*LineLog, *sqlgraph.CreateSpec) {
	var (
		_node = &LineLog{config: llc.config}
		_spec = sqlgraph.NewCreateSpec(linelog.Table, sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt))
	)
	if value, ok := llc.mutation.Action(); ok {
		_spec.SetField(linelog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := llc.mutation.Message(); ok {
		_spec.SetField(linelog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := llc.mutation.CreatedAt(); ok {
		_spec.SetField(linelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := llc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linelog.OwnerTable,
			Columns: []string{linelog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.line_user_linelogs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LineLogCreateBulk is the builder for creating many LineLog entities in bulk.
type LineLogCreateBulk struct {
	config
	builders []*LineLogCreate
}

// Save creates the LineLog entities in the database.
func (llcb *LineLogCreateBulk) Save(ctx context.Context) ([]*LineLog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(llcb.builders))
	nodes := make([]*LineLog, len(llcb.builders))
	mutators := make([]Mutator, len(llcb.builders))
	for i := range llcb.builders {
		func(i int, root context.Context) {
			builder := llcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LineLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, llcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, llcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, llcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (llcb *LineLogCreateBulk) SaveX(ctx context.Context) []*LineLog {
	v, err := llcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (llcb *LineLogCreateBulk) Exec(ctx context.Context) error {
	_, err := llcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (llcb *LineLogCreateBulk) ExecX(ctx context.Context) {
	if err := llcb.Exec(ctx); err != nil {
		panic(err)
	}
}
