// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/linelog"
	"entdemo/ent/lineuser"
	"entdemo/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineLogQuery is the builder for querying LineLog entities.
type LineLogQuery struct {
	config
	ctx        *QueryContext
	order      []linelog.OrderOption
	inters     []Interceptor
	predicates []predicate.LineLog
	withOwner  *LineUserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LineLogQuery builder.
func (llq *LineLogQuery) Where(ps ...predicate.LineLog) *LineLogQuery {
	llq.predicates = append(llq.predicates, ps...)
	return llq
}

// Limit the number of records to be returned by this query.
func (llq *LineLogQuery) Limit(limit int) *LineLogQuery {
	llq.ctx.Limit = &limit
	return llq
}

// Offset to start from.
func (llq *LineLogQuery) Offset(offset int) *LineLogQuery {
	llq.ctx.Offset = &offset
	return llq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (llq *LineLogQuery) Unique(unique bool) *LineLogQuery {
	llq.ctx.Unique = &unique
	return llq
}

// Order specifies how the records should be ordered.
func (llq *LineLogQuery) Order(o ...linelog.OrderOption) *LineLogQuery {
	llq.order = append(llq.order, o...)
	return llq
}

// QueryOwner chains the current query on the "owner" edge.
func (llq *LineLogQuery) QueryOwner() *LineUserQuery {
	query := (&LineUserClient{config: llq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := llq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := llq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(linelog.Table, linelog.FieldID, selector),
			sqlgraph.To(lineuser.Table, lineuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, linelog.OwnerTable, linelog.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(llq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LineLog entity from the query.
// Returns a *NotFoundError when no LineLog was found.
func (llq *LineLogQuery) First(ctx context.Context) (*LineLog, error) {
	nodes, err := llq.Limit(1).All(setContextOp(ctx, llq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{linelog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (llq *LineLogQuery) FirstX(ctx context.Context) *LineLog {
	node, err := llq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LineLog ID from the query.
// Returns a *NotFoundError when no LineLog ID was found.
func (llq *LineLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = llq.Limit(1).IDs(setContextOp(ctx, llq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{linelog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (llq *LineLogQuery) FirstIDX(ctx context.Context) int {
	id, err := llq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LineLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LineLog entity is found.
// Returns a *NotFoundError when no LineLog entities are found.
func (llq *LineLogQuery) Only(ctx context.Context) (*LineLog, error) {
	nodes, err := llq.Limit(2).All(setContextOp(ctx, llq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{linelog.Label}
	default:
		return nil, &NotSingularError{linelog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (llq *LineLogQuery) OnlyX(ctx context.Context) *LineLog {
	node, err := llq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LineLog ID in the query.
// Returns a *NotSingularError when more than one LineLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (llq *LineLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = llq.Limit(2).IDs(setContextOp(ctx, llq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{linelog.Label}
	default:
		err = &NotSingularError{linelog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (llq *LineLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := llq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LineLogs.
func (llq *LineLogQuery) All(ctx context.Context) ([]*LineLog, error) {
	ctx = setContextOp(ctx, llq.ctx, "All")
	if err := llq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LineLog, *LineLogQuery]()
	return withInterceptors[[]*LineLog](ctx, llq, qr, llq.inters)
}

// AllX is like All, but panics if an error occurs.
func (llq *LineLogQuery) AllX(ctx context.Context) []*LineLog {
	nodes, err := llq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LineLog IDs.
func (llq *LineLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if llq.ctx.Unique == nil && llq.path != nil {
		llq.Unique(true)
	}
	ctx = setContextOp(ctx, llq.ctx, "IDs")
	if err = llq.Select(linelog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (llq *LineLogQuery) IDsX(ctx context.Context) []int {
	ids, err := llq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (llq *LineLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, llq.ctx, "Count")
	if err := llq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, llq, querierCount[*LineLogQuery](), llq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (llq *LineLogQuery) CountX(ctx context.Context) int {
	count, err := llq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (llq *LineLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, llq.ctx, "Exist")
	switch _, err := llq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (llq *LineLogQuery) ExistX(ctx context.Context) bool {
	exist, err := llq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LineLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (llq *LineLogQuery) Clone() *LineLogQuery {
	if llq == nil {
		return nil
	}
	return &LineLogQuery{
		config:     llq.config,
		ctx:        llq.ctx.Clone(),
		order:      append([]linelog.OrderOption{}, llq.order...),
		inters:     append([]Interceptor{}, llq.inters...),
		predicates: append([]predicate.LineLog{}, llq.predicates...),
		withOwner:  llq.withOwner.Clone(),
		// clone intermediate query.
		sql:  llq.sql.Clone(),
		path: llq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (llq *LineLogQuery) WithOwner(opts ...func(*LineUserQuery)) *LineLogQuery {
	query := (&LineUserClient{config: llq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	llq.withOwner = query
	return llq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Action string `json:"action,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LineLog.Query().
//		GroupBy(linelog.FieldAction).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (llq *LineLogQuery) GroupBy(field string, fields ...string) *LineLogGroupBy {
	llq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LineLogGroupBy{build: llq}
	grbuild.flds = &llq.ctx.Fields
	grbuild.label = linelog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Action string `json:"action,omitempty"`
//	}
//
//	client.LineLog.Query().
//		Select(linelog.FieldAction).
//		Scan(ctx, &v)
func (llq *LineLogQuery) Select(fields ...string) *LineLogSelect {
	llq.ctx.Fields = append(llq.ctx.Fields, fields...)
	sbuild := &LineLogSelect{LineLogQuery: llq}
	sbuild.label = linelog.Label
	sbuild.flds, sbuild.scan = &llq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LineLogSelect configured with the given aggregations.
func (llq *LineLogQuery) Aggregate(fns ...AggregateFunc) *LineLogSelect {
	return llq.Select().Aggregate(fns...)
}

func (llq *LineLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range llq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, llq); err != nil {
				return err
			}
		}
	}
	for _, f := range llq.ctx.Fields {
		if !linelog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if llq.path != nil {
		prev, err := llq.path(ctx)
		if err != nil {
			return err
		}
		llq.sql = prev
	}
	return nil
}

func (llq *LineLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LineLog, error) {
	var (
		nodes       = []*LineLog{}
		withFKs     = llq.withFKs
		_spec       = llq.querySpec()
		loadedTypes = [1]bool{
			llq.withOwner != nil,
		}
	)
	if llq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, linelog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LineLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LineLog{config: llq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, llq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := llq.withOwner; query != nil {
		if err := llq.loadOwner(ctx, query, nodes, nil,
			func(n *LineLog, e *LineUser) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (llq *LineLogQuery) loadOwner(ctx context.Context, query *LineUserQuery, nodes []*LineLog, init func(*LineLog), assign func(*LineLog, *LineUser)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LineLog)
	for i := range nodes {
		if nodes[i].line_user_linelogs == nil {
			continue
		}
		fk := *nodes[i].line_user_linelogs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(lineuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "line_user_linelogs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (llq *LineLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := llq.querySpec()
	_spec.Node.Columns = llq.ctx.Fields
	if len(llq.ctx.Fields) > 0 {
		_spec.Unique = llq.ctx.Unique != nil && *llq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, llq.driver, _spec)
}

func (llq *LineLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(linelog.Table, linelog.Columns, sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt))
	_spec.From = llq.sql
	if unique := llq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if llq.path != nil {
		_spec.Unique = true
	}
	if fields := llq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linelog.FieldID)
		for i := range fields {
			if fields[i] != linelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := llq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := llq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := llq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := llq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (llq *LineLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(llq.driver.Dialect())
	t1 := builder.Table(linelog.Table)
	columns := llq.ctx.Fields
	if len(columns) == 0 {
		columns = linelog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if llq.sql != nil {
		selector = llq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if llq.ctx.Unique != nil && *llq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range llq.predicates {
		p(selector)
	}
	for _, p := range llq.order {
		p(selector)
	}
	if offset := llq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := llq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LineLogGroupBy is the group-by builder for LineLog entities.
type LineLogGroupBy struct {
	selector
	build *LineLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (llgb *LineLogGroupBy) Aggregate(fns ...AggregateFunc) *LineLogGroupBy {
	llgb.fns = append(llgb.fns, fns...)
	return llgb
}

// Scan applies the selector query and scans the result into the given value.
func (llgb *LineLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, llgb.build.ctx, "GroupBy")
	if err := llgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LineLogQuery, *LineLogGroupBy](ctx, llgb.build, llgb, llgb.build.inters, v)
}

func (llgb *LineLogGroupBy) sqlScan(ctx context.Context, root *LineLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(llgb.fns))
	for _, fn := range llgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*llgb.flds)+len(llgb.fns))
		for _, f := range *llgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*llgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := llgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LineLogSelect is the builder for selecting fields of LineLog entities.
type LineLogSelect struct {
	*LineLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lls *LineLogSelect) Aggregate(fns ...AggregateFunc) *LineLogSelect {
	lls.fns = append(lls.fns, fns...)
	return lls
}

// Scan applies the selector query and scans the result into the given value.
func (lls *LineLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lls.ctx, "Select")
	if err := lls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LineLogQuery, *LineLogSelect](ctx, lls.LineLogQuery, lls, lls.inters, v)
}

func (lls *LineLogSelect) sqlScan(ctx context.Context, root *LineLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lls.fns))
	for _, fn := range lls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
