// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entdemo/ent/creditlater"
	"entdemo/ent/lineuser"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LineUser is the model entity for the LineUser schema.
type LineUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId string `json:"userId,omitempty"`
	// DisplyaName holds the value of the "displyaName" field.
	DisplyaName string `json:"displyaName,omitempty"`
	// RegisteredAt holds the value of the "registered_at" field.
	RegisteredAt time.Time `json:"registered_at,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LineUserQuery when eager-loading is set.
	Edges        LineUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LineUserEdges holds the relations/edges for other nodes in the graph.
type LineUserEdges struct {
	// Linelogs holds the value of the linelogs edge.
	Linelogs []*LineLog `json:"linelogs,omitempty"`
	// Creditlaters holds the value of the creditlaters edge.
	Creditlaters *CreditLater `json:"creditlaters,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LinelogsOrErr returns the Linelogs value or an error if the edge
// was not loaded in eager-loading.
func (e LineUserEdges) LinelogsOrErr() ([]*LineLog, error) {
	if e.loadedTypes[0] {
		return e.Linelogs, nil
	}
	return nil, &NotLoadedError{edge: "linelogs"}
}

// CreditlatersOrErr returns the Creditlaters value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LineUserEdges) CreditlatersOrErr() (*CreditLater, error) {
	if e.loadedTypes[1] {
		if e.Creditlaters == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: creditlater.Label}
		}
		return e.Creditlaters, nil
	}
	return nil, &NotLoadedError{edge: "creditlaters"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LineUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lineuser.FieldActive:
			values[i] = new(sql.NullBool)
		case lineuser.FieldID:
			values[i] = new(sql.NullInt64)
		case lineuser.FieldUserId, lineuser.FieldDisplyaName:
			values[i] = new(sql.NullString)
		case lineuser.FieldRegisteredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LineUser fields.
func (lu *LineUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lineuser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lu.ID = int(value.Int64)
		case lineuser.FieldUserId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				lu.UserId = value.String
			}
		case lineuser.FieldDisplyaName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field displyaName", values[i])
			} else if value.Valid {
				lu.DisplyaName = value.String
			}
		case lineuser.FieldRegisteredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field registered_at", values[i])
			} else if value.Valid {
				lu.RegisteredAt = value.Time
			}
		case lineuser.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				lu.Active = value.Bool
			}
		default:
			lu.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LineUser.
// This includes values selected through modifiers, order, etc.
func (lu *LineUser) Value(name string) (ent.Value, error) {
	return lu.selectValues.Get(name)
}

// QueryLinelogs queries the "linelogs" edge of the LineUser entity.
func (lu *LineUser) QueryLinelogs() *LineLogQuery {
	return NewLineUserClient(lu.config).QueryLinelogs(lu)
}

// QueryCreditlaters queries the "creditlaters" edge of the LineUser entity.
func (lu *LineUser) QueryCreditlaters() *CreditLaterQuery {
	return NewLineUserClient(lu.config).QueryCreditlaters(lu)
}

// Update returns a builder for updating this LineUser.
// Note that you need to call LineUser.Unwrap() before calling this method if this LineUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (lu *LineUser) Update() *LineUserUpdateOne {
	return NewLineUserClient(lu.config).UpdateOne(lu)
}

// Unwrap unwraps the LineUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lu *LineUser) Unwrap() *LineUser {
	_tx, ok := lu.config.driver.(*txDriver)
	if !ok {
		panic("ent: LineUser is not a transactional entity")
	}
	lu.config.driver = _tx.drv
	return lu
}

// String implements the fmt.Stringer.
func (lu *LineUser) String() string {
	var builder strings.Builder
	builder.WriteString("LineUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lu.ID))
	builder.WriteString("userId=")
	builder.WriteString(lu.UserId)
	builder.WriteString(", ")
	builder.WriteString("displyaName=")
	builder.WriteString(lu.DisplyaName)
	builder.WriteString(", ")
	builder.WriteString("registered_at=")
	builder.WriteString(lu.RegisteredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", lu.Active))
	builder.WriteByte(')')
	return builder.String()
}

// LineUsers is a parsable slice of LineUser.
type LineUsers []*LineUser
