// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/car"
	"entdemo/ent/creditlater"
	"entdemo/ent/group"
	"entdemo/ent/linelog"
	"entdemo/ent/lineuser"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineUserCreate is the builder for creating a LineUser entity.
type LineUserCreate struct {
	config
	mutation *LineUserMutation
	hooks    []Hook
}

// SetUserId sets the "userId" field.
func (luc *LineUserCreate) SetUserId(s string) *LineUserCreate {
	luc.mutation.SetUserId(s)
	return luc
}

// SetDisplyaName sets the "displyaName" field.
func (luc *LineUserCreate) SetDisplyaName(s string) *LineUserCreate {
	luc.mutation.SetDisplyaName(s)
	return luc
}

// SetRegisteredAt sets the "registered_at" field.
func (luc *LineUserCreate) SetRegisteredAt(t time.Time) *LineUserCreate {
	luc.mutation.SetRegisteredAt(t)
	return luc
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (luc *LineUserCreate) SetNillableRegisteredAt(t *time.Time) *LineUserCreate {
	if t != nil {
		luc.SetRegisteredAt(*t)
	}
	return luc
}

// SetActive sets the "active" field.
func (luc *LineUserCreate) SetActive(b bool) *LineUserCreate {
	luc.mutation.SetActive(b)
	return luc
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (luc *LineUserCreate) SetNillableActive(b *bool) *LineUserCreate {
	if b != nil {
		luc.SetActive(*b)
	}
	return luc
}

// AddLinelogIDs adds the "linelogs" edge to the LineLog entity by IDs.
func (luc *LineUserCreate) AddLinelogIDs(ids ...int) *LineUserCreate {
	luc.mutation.AddLinelogIDs(ids...)
	return luc
}

// AddLinelogs adds the "linelogs" edges to the LineLog entity.
func (luc *LineUserCreate) AddLinelogs(l ...*LineLog) *LineUserCreate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luc.AddLinelogIDs(ids...)
}

// SetCreditlatersID sets the "creditlaters" edge to the CreditLater entity by ID.
func (luc *LineUserCreate) SetCreditlatersID(id int) *LineUserCreate {
	luc.mutation.SetCreditlatersID(id)
	return luc
}

// SetNillableCreditlatersID sets the "creditlaters" edge to the CreditLater entity by ID if the given value is not nil.
func (luc *LineUserCreate) SetNillableCreditlatersID(id *int) *LineUserCreate {
	if id != nil {
		luc = luc.SetCreditlatersID(*id)
	}
	return luc
}

// SetCreditlaters sets the "creditlaters" edge to the CreditLater entity.
func (luc *LineUserCreate) SetCreditlaters(c *CreditLater) *LineUserCreate {
	return luc.SetCreditlatersID(c.ID)
}

// AddCarIDs adds the "cars" edge to the Car entity by IDs.
func (luc *LineUserCreate) AddCarIDs(ids ...int) *LineUserCreate {
	luc.mutation.AddCarIDs(ids...)
	return luc
}

// AddCars adds the "cars" edges to the Car entity.
func (luc *LineUserCreate) AddCars(c ...*Car) *LineUserCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return luc.AddCarIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (luc *LineUserCreate) AddGroupIDs(ids ...int) *LineUserCreate {
	luc.mutation.AddGroupIDs(ids...)
	return luc
}

// AddGroups adds the "groups" edges to the Group entity.
func (luc *LineUserCreate) AddGroups(g ...*Group) *LineUserCreate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return luc.AddGroupIDs(ids...)
}

// Mutation returns the LineUserMutation object of the builder.
func (luc *LineUserCreate) Mutation() *LineUserMutation {
	return luc.mutation
}

// Save creates the LineUser in the database.
func (luc *LineUserCreate) Save(ctx context.Context) (*LineUser, error) {
	luc.defaults()
	return withHooks(ctx, luc.sqlSave, luc.mutation, luc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (luc *LineUserCreate) SaveX(ctx context.Context) *LineUser {
	v, err := luc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (luc *LineUserCreate) Exec(ctx context.Context) error {
	_, err := luc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luc *LineUserCreate) ExecX(ctx context.Context) {
	if err := luc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (luc *LineUserCreate) defaults() {
	if _, ok := luc.mutation.RegisteredAt(); !ok {
		v := lineuser.DefaultRegisteredAt
		luc.mutation.SetRegisteredAt(v)
	}
	if _, ok := luc.mutation.Active(); !ok {
		v := lineuser.DefaultActive
		luc.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luc *LineUserCreate) check() error {
	if _, ok := luc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New(`ent: missing required field "LineUser.userId"`)}
	}
	if v, ok := luc.mutation.UserId(); ok {
		if err := lineuser.UserIdValidator(v); err != nil {
			return &ValidationError{Name: "userId", err: fmt.Errorf(`ent: validator failed for field "LineUser.userId": %w`, err)}
		}
	}
	if _, ok := luc.mutation.DisplyaName(); !ok {
		return &ValidationError{Name: "displyaName", err: errors.New(`ent: missing required field "LineUser.displyaName"`)}
	}
	if _, ok := luc.mutation.RegisteredAt(); !ok {
		return &ValidationError{Name: "registered_at", err: errors.New(`ent: missing required field "LineUser.registered_at"`)}
	}
	if _, ok := luc.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "LineUser.active"`)}
	}
	return nil
}

func (luc *LineUserCreate) sqlSave(ctx context.Context) (*LineUser, error) {
	if err := luc.check(); err != nil {
		return nil, err
	}
	_node, _spec := luc.createSpec()
	if err := sqlgraph.CreateNode(ctx, luc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	luc.mutation.id = &_node.ID
	luc.mutation.done = true
	return _node, nil
}

func (luc *LineUserCreate) createSpec() (*LineUser, *sqlgraph.CreateSpec) {
	var (
		_node = &LineUser{config: luc.config}
		_spec = sqlgraph.NewCreateSpec(lineuser.Table, sqlgraph.NewFieldSpec(lineuser.FieldID, field.TypeInt))
	)
	if value, ok := luc.mutation.UserId(); ok {
		_spec.SetField(lineuser.FieldUserId, field.TypeString, value)
		_node.UserId = value
	}
	if value, ok := luc.mutation.DisplyaName(); ok {
		_spec.SetField(lineuser.FieldDisplyaName, field.TypeString, value)
		_node.DisplyaName = value
	}
	if value, ok := luc.mutation.RegisteredAt(); ok {
		_spec.SetField(lineuser.FieldRegisteredAt, field.TypeTime, value)
		_node.RegisteredAt = value
	}
	if value, ok := luc.mutation.Active(); ok {
		_spec.SetField(lineuser.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if nodes := luc.mutation.LinelogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.LinelogsTable,
			Columns: []string{lineuser.LinelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := luc.mutation.CreditlatersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lineuser.CreditlatersTable,
			Columns: []string{lineuser.CreditlatersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditlater.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := luc.mutation.CarsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lineuser.CarsTable,
			Columns: []string{lineuser.CarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := luc.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lineuser.GroupsTable,
			Columns: lineuser.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LineUserCreateBulk is the builder for creating many LineUser entities in bulk.
type LineUserCreateBulk struct {
	config
	builders []*LineUserCreate
}

// Save creates the LineUser entities in the database.
func (lucb *LineUserCreateBulk) Save(ctx context.Context) ([]*LineUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lucb.builders))
	nodes := make([]*LineUser, len(lucb.builders))
	mutators := make([]Mutator, len(lucb.builders))
	for i := range lucb.builders {
		func(i int, root context.Context) {
			builder := lucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LineUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lucb *LineUserCreateBulk) SaveX(ctx context.Context) []*LineUser {
	v, err := lucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lucb *LineUserCreateBulk) Exec(ctx context.Context) error {
	_, err := lucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lucb *LineUserCreateBulk) ExecX(ctx context.Context) {
	if err := lucb.Exec(ctx); err != nil {
		panic(err)
	}
}
