// Code generated by ent, DO NOT EDIT.

package lineuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lineuser type in the database.
	Label = "line_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserId holds the string denoting the userid field in the database.
	FieldUserId = "user_id"
	// FieldDisplyaName holds the string denoting the displyaname field in the database.
	FieldDisplyaName = "displya_name"
	// FieldRegisteredAt holds the string denoting the registered_at field in the database.
	FieldRegisteredAt = "registered_at"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// EdgeLinelogs holds the string denoting the linelogs edge name in mutations.
	EdgeLinelogs = "linelogs"
	// EdgeCreditlaters holds the string denoting the creditlaters edge name in mutations.
	EdgeCreditlaters = "creditlaters"
	// EdgeCars holds the string denoting the cars edge name in mutations.
	EdgeCars = "cars"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// Table holds the table name of the lineuser in the database.
	Table = "line_users"
	// LinelogsTable is the table that holds the linelogs relation/edge.
	LinelogsTable = "line_logs"
	// LinelogsInverseTable is the table name for the LineLog entity.
	// It exists in this package in order to avoid circular dependency with the "linelog" package.
	LinelogsInverseTable = "line_logs"
	// LinelogsColumn is the table column denoting the linelogs relation/edge.
	LinelogsColumn = "line_user_linelogs"
	// CreditlatersTable is the table that holds the creditlaters relation/edge.
	CreditlatersTable = "credit_laters"
	// CreditlatersInverseTable is the table name for the CreditLater entity.
	// It exists in this package in order to avoid circular dependency with the "creditlater" package.
	CreditlatersInverseTable = "credit_laters"
	// CreditlatersColumn is the table column denoting the creditlaters relation/edge.
	CreditlatersColumn = "line_user_creditlaters"
	// CarsTable is the table that holds the cars relation/edge.
	CarsTable = "cars"
	// CarsInverseTable is the table name for the Car entity.
	// It exists in this package in order to avoid circular dependency with the "car" package.
	CarsInverseTable = "cars"
	// CarsColumn is the table column denoting the cars relation/edge.
	CarsColumn = "line_user_cars"
	// GroupsTable is the table that holds the groups relation/edge. The primary key declared below.
	GroupsTable = "group_lineusers"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
)

// Columns holds all SQL columns for lineuser fields.
var Columns = []string{
	FieldID,
	FieldUserId,
	FieldDisplyaName,
	FieldRegisteredAt,
	FieldActive,
}

var (
	// GroupsPrimaryKey and GroupsColumn2 are the table columns denoting the
	// primary key for the groups relation (M2M).
	GroupsPrimaryKey = []string{"group_id", "line_user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIdValidator is a validator for the "userId" field. It is called by the builders before save.
	UserIdValidator func(string) error
	// DefaultRegisteredAt holds the default value on creation for the "registered_at" field.
	DefaultRegisteredAt time.Time
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
)

// OrderOption defines the ordering options for the LineUser queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserId orders the results by the userId field.
func ByUserId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserId, opts...).ToFunc()
}

// ByDisplyaName orders the results by the displyaName field.
func ByDisplyaName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplyaName, opts...).ToFunc()
}

// ByRegisteredAt orders the results by the registered_at field.
func ByRegisteredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredAt, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByLinelogsCount orders the results by linelogs count.
func ByLinelogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLinelogsStep(), opts...)
	}
}

// ByLinelogs orders the results by linelogs terms.
func ByLinelogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinelogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreditlatersField orders the results by creditlaters field.
func ByCreditlatersField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreditlatersStep(), sql.OrderByField(field, opts...))
	}
}

// ByCarsCount orders the results by cars count.
func ByCarsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCarsStep(), opts...)
	}
}

// ByCars orders the results by cars terms.
func ByCars(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCarsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLinelogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinelogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LinelogsTable, LinelogsColumn),
	)
}
func newCreditlatersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreditlatersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, CreditlatersTable, CreditlatersColumn),
	)
}
func newCarsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CarsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CarsTable, CarsColumn),
	)
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, GroupsTable, GroupsPrimaryKey...),
	)
}
