// Code generated by ent, DO NOT EDIT.

package lineuser

import (
	"entdemo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LineUser {
	return predicate.LineUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LineUser {
	return predicate.LineUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LineUser {
	return predicate.LineUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LineUser {
	return predicate.LineUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LineUser {
	return predicate.LineUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LineUser {
	return predicate.LineUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LineUser {
	return predicate.LineUser(sql.FieldLTE(FieldID, id))
}

// UserId applies equality check predicate on the "userId" field. It's identical to UserIdEQ.
func UserId(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldUserId, v))
}

// DisplyaName applies equality check predicate on the "displyaName" field. It's identical to DisplyaNameEQ.
func DisplyaName(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldDisplyaName, v))
}

// RegisteredAt applies equality check predicate on the "registered_at" field. It's identical to RegisteredAtEQ.
func RegisteredAt(v time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldRegisteredAt, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldActive, v))
}

// UserIdEQ applies the EQ predicate on the "userId" field.
func UserIdEQ(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "userId" field.
func UserIdNEQ(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "userId" field.
func UserIdIn(vs ...string) predicate.LineUser {
	return predicate.LineUser(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "userId" field.
func UserIdNotIn(vs ...string) predicate.LineUser {
	return predicate.LineUser(sql.FieldNotIn(FieldUserId, vs...))
}

// UserIdGT applies the GT predicate on the "userId" field.
func UserIdGT(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldGT(FieldUserId, v))
}

// UserIdGTE applies the GTE predicate on the "userId" field.
func UserIdGTE(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldGTE(FieldUserId, v))
}

// UserIdLT applies the LT predicate on the "userId" field.
func UserIdLT(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldLT(FieldUserId, v))
}

// UserIdLTE applies the LTE predicate on the "userId" field.
func UserIdLTE(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldLTE(FieldUserId, v))
}

// UserIdContains applies the Contains predicate on the "userId" field.
func UserIdContains(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldContains(FieldUserId, v))
}

// UserIdHasPrefix applies the HasPrefix predicate on the "userId" field.
func UserIdHasPrefix(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldHasPrefix(FieldUserId, v))
}

// UserIdHasSuffix applies the HasSuffix predicate on the "userId" field.
func UserIdHasSuffix(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldHasSuffix(FieldUserId, v))
}

// UserIdEqualFold applies the EqualFold predicate on the "userId" field.
func UserIdEqualFold(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldEqualFold(FieldUserId, v))
}

// UserIdContainsFold applies the ContainsFold predicate on the "userId" field.
func UserIdContainsFold(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldContainsFold(FieldUserId, v))
}

// DisplyaNameEQ applies the EQ predicate on the "displyaName" field.
func DisplyaNameEQ(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldDisplyaName, v))
}

// DisplyaNameNEQ applies the NEQ predicate on the "displyaName" field.
func DisplyaNameNEQ(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldNEQ(FieldDisplyaName, v))
}

// DisplyaNameIn applies the In predicate on the "displyaName" field.
func DisplyaNameIn(vs ...string) predicate.LineUser {
	return predicate.LineUser(sql.FieldIn(FieldDisplyaName, vs...))
}

// DisplyaNameNotIn applies the NotIn predicate on the "displyaName" field.
func DisplyaNameNotIn(vs ...string) predicate.LineUser {
	return predicate.LineUser(sql.FieldNotIn(FieldDisplyaName, vs...))
}

// DisplyaNameGT applies the GT predicate on the "displyaName" field.
func DisplyaNameGT(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldGT(FieldDisplyaName, v))
}

// DisplyaNameGTE applies the GTE predicate on the "displyaName" field.
func DisplyaNameGTE(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldGTE(FieldDisplyaName, v))
}

// DisplyaNameLT applies the LT predicate on the "displyaName" field.
func DisplyaNameLT(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldLT(FieldDisplyaName, v))
}

// DisplyaNameLTE applies the LTE predicate on the "displyaName" field.
func DisplyaNameLTE(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldLTE(FieldDisplyaName, v))
}

// DisplyaNameContains applies the Contains predicate on the "displyaName" field.
func DisplyaNameContains(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldContains(FieldDisplyaName, v))
}

// DisplyaNameHasPrefix applies the HasPrefix predicate on the "displyaName" field.
func DisplyaNameHasPrefix(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldHasPrefix(FieldDisplyaName, v))
}

// DisplyaNameHasSuffix applies the HasSuffix predicate on the "displyaName" field.
func DisplyaNameHasSuffix(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldHasSuffix(FieldDisplyaName, v))
}

// DisplyaNameEqualFold applies the EqualFold predicate on the "displyaName" field.
func DisplyaNameEqualFold(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldEqualFold(FieldDisplyaName, v))
}

// DisplyaNameContainsFold applies the ContainsFold predicate on the "displyaName" field.
func DisplyaNameContainsFold(v string) predicate.LineUser {
	return predicate.LineUser(sql.FieldContainsFold(FieldDisplyaName, v))
}

// RegisteredAtEQ applies the EQ predicate on the "registered_at" field.
func RegisteredAtEQ(v time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldRegisteredAt, v))
}

// RegisteredAtNEQ applies the NEQ predicate on the "registered_at" field.
func RegisteredAtNEQ(v time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldNEQ(FieldRegisteredAt, v))
}

// RegisteredAtIn applies the In predicate on the "registered_at" field.
func RegisteredAtIn(vs ...time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldIn(FieldRegisteredAt, vs...))
}

// RegisteredAtNotIn applies the NotIn predicate on the "registered_at" field.
func RegisteredAtNotIn(vs ...time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldNotIn(FieldRegisteredAt, vs...))
}

// RegisteredAtGT applies the GT predicate on the "registered_at" field.
func RegisteredAtGT(v time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldGT(FieldRegisteredAt, v))
}

// RegisteredAtGTE applies the GTE predicate on the "registered_at" field.
func RegisteredAtGTE(v time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldGTE(FieldRegisteredAt, v))
}

// RegisteredAtLT applies the LT predicate on the "registered_at" field.
func RegisteredAtLT(v time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldLT(FieldRegisteredAt, v))
}

// RegisteredAtLTE applies the LTE predicate on the "registered_at" field.
func RegisteredAtLTE(v time.Time) predicate.LineUser {
	return predicate.LineUser(sql.FieldLTE(FieldRegisteredAt, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.LineUser {
	return predicate.LineUser(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.LineUser {
	return predicate.LineUser(sql.FieldNEQ(FieldActive, v))
}

// HasLinelogs applies the HasEdge predicate on the "linelogs" edge.
func HasLinelogs() predicate.LineUser {
	return predicate.LineUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LinelogsTable, LinelogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinelogsWith applies the HasEdge predicate on the "linelogs" edge with a given conditions (other predicates).
func HasLinelogsWith(preds ...predicate.LineLog) predicate.LineUser {
	return predicate.LineUser(func(s *sql.Selector) {
		step := newLinelogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreditlaters applies the HasEdge predicate on the "creditlaters" edge.
func HasCreditlaters() predicate.LineUser {
	return predicate.LineUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, CreditlatersTable, CreditlatersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreditlatersWith applies the HasEdge predicate on the "creditlaters" edge with a given conditions (other predicates).
func HasCreditlatersWith(preds ...predicate.CreditLater) predicate.LineUser {
	return predicate.LineUser(func(s *sql.Selector) {
		step := newCreditlatersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LineUser) predicate.LineUser {
	return predicate.LineUser(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LineUser) predicate.LineUser {
	return predicate.LineUser(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LineUser) predicate.LineUser {
	return predicate.LineUser(func(s *sql.Selector) {
		p(s.Not())
	})
}
