// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// CreditLater is the predicate function for creditlater builders.
type CreditLater func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// LineLog is the predicate function for linelog builders.
type LineLog func(*sql.Selector)

// LineUser is the predicate function for lineuser builders.
type LineUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
